layout_spectrum: 0.5259956756632517
typography_spectrum: 0.495258098525908
color:
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
  brandStrength: 0.17500444246059524
  lightness: 0.09596106200395982
  saturation: 0.5393169213148148
  rhythmicContrast: 0.36775761376273364
coverPrefs:
  filter: false
content_rating:
  adult: false
opengraph:
  image: null
  type: ''
  appId: ''
analytics:
  google: UA-75011199-1
  facebook: null
  twitter: null
author:
  name: ITALIAN LINKG GENERAL TRADING LLC
  url: 'http://www.italianlink.com/'
  email: info@italianlink.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fe5b5698-36d4-4241-ae71-623283c45378.png
name: ITALIAN LINK L.L.C.
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About us
    id: be47c6ee-362d-4b90-87e3-97421cda9938
    type: content
  - name: Our Stones
    id: 4bba7860-f9a1-4026-9914-c16038d42323
    type: content
  - name: Visit our Facebook Page
    url: 'https://www.facebook.com/ITALIAN.LINK.LLC'
    type: external
  - name: Contact us
    id: fb500b03-db2f-438a-98d4-90a77a3d95b7
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7d22a17d-b241-4344-a532-d81c794d6747.png
title: We are your Italian stone suppliers
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://s3-us-west-2.amazonaws.com/the-grid-img/p/e75909424a5d6a9d17d48037234e564c4a0990b0.jpg">
    src: >-
      https://s3-us-west-2.amazonaws.com/the-grid-img/p/e75909424a5d6a9d17d48037234e564c4a0990b0.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://s3-us-west-2.amazonaws.com'
        name: .s3-us-west-2.amazonaws.com
        favicon: null
        domain: s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: '"Linking the World to Quality..."'
purpose:
  - type: contact
    url: 'mailto:info@italianlink.com'
    label: Contact us
  - type: external
    url: 'https://www.facebook.com/ITALIAN.LINK.LLC'
    label: Visit our Facebook Page
url: 'http://italianlink.com/'
github: true
