typography_spectrum: 0.37665
content_rating:
  adult: false
color:
  brandColors:
    - '#ffffff'
    - '#024d8d'
    - '#231f20'
    - '#7c8fb7'
    - '#b0b1b2'
  brandStrength: 0
  lightness: 0.3125
  saturation: 1
  rhythmicContrast: 0
opengraph:
  image: null
  type: ''
  appId: ''
layout_spectrum: 0.30485
analytics:
  google: UA-75011199-1
  facebook: null
  twitter: null
author:
  name: ''
  url: ''
  email: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/966945c0-c5c3-4d50-8ed9-5367c6b7f8b0.png
name: ITALIAN LINK LLC
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ITALIAN LINK LLC  "Linking the World to Quality"
description: Stone
purpose: []
