name: ITALIAN LINK LLC
favicon: null
layout_spectrum: 0.75001
typography_spectrum: 0.25176
content_rating:
  adult: false
author:
  name: ''
  url: ''
  email: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/966945c0-c5c3-4d50-8ed9-5367c6b7f8b0.png
navigation:
  - name: Visit our Facebook Page
    url: 'https://www.facebook.com/ITALIAN.LINK.LLC'
    type: external
title: ITALIAN LINK LLC  "Linking the World to Quality"
description: Stone Suppliers
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75011199-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: ''
  appId: ''
color:
  brandColors:
    - '#ffffff'
    - '#024d8d'
    - '#231f20'
    - '#7c8fb7'
    - '#b0b1b2'
  brandStrength: 0
  lightness: 0.25
  saturation: 1
  rhythmicContrast: 0
purpose: []
