name: ITALIAN LINK LLC
favicon: null
layout_spectrum: 0.73714
typography_spectrum: 0.8185
title: ITALIAN LINK LLC - Linking the World to Quality...
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#024d8d'
    - '#231f20'
    - '#7c8fb7'
    - '#b0b1b2'
  brandStrength: 0
  lightness: 0.3125
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
