name: ITALIAN LINK LLC
favicon: null
layout_spectrum: 0.88891
typography_spectrum: 0.8491
title: Linking the World to Quality...
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#024d8d'
    - '#909191'
    - '#009e57'
    - '#f60a29'
    - '#ffffff'
  brandStrength: 0.875
  lightness: 0.875
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
