analytics:
  google: UA-75011199-1
color:
  brandColors:
    - '#ffffff'
    - '#024d8d'
    - '#231f20'
    - '#7c8fb7'
    - '#b0b1b2'
  brandStrength: 0
  lightness: 0.5
  rhythmicContrast: 0
  saturation: 1
cta: {}
layout_spectrum: 0.79955
name: ITALIAN LINK LLC
opengraph: {}
purpose: []
typography_spectrum: 0.39405
