name: ITALIAN LINK LLC
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/966945c0-c5c3-4d50-8ed9-5367c6b7f8b0.png
layout_spectrum: 0.4449718603864312
typography_spectrum: 0.8174214141909033
cta: {}
analytics:
  google: UA-75011199-1
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#ffffff'
    - '#024d8d'
    - '#231f20'
    - '#7c8fb7'
    - '#b0b1b2'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0
purpose: []
title: ''
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: false
