name: ITALIAN LINK LLC
favicon: null
layout_spectrum: 0.30485
typography_spectrum: 0.37665
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/966945c0-c5c3-4d50-8ed9-5367c6b7f8b0.png
title: ''
author:
  name: ''
  url: ''
  email: ''
content_rating:
  adult: false
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-75011199-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: ''
  appId: ''
color:
  brandColors:
    - '#ffffff'
    - '#024d8d'
    - '#231f20'
    - '#7c8fb7'
    - '#b0b1b2'
  brandStrength: 0
  lightness: 0.375
  saturation: 1
  rhythmicContrast: 0
purpose: []
