name: ITALIAN LINK LLC
favicon: null
layout_spectrum: 0.25174
typography_spectrum: 0.8491
title: Linking the World to Quality...
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#024d8d'
    - '#909191'
    - '#ffffff'
    - '#009e57'
    - '#f60a29'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
